services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: interpol_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  producer:
    build: .
    container_name: interpol_producer
    command: python veri_cek.py
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PERIYOT_SANIYESI=30

  web_server:
    build: .
    container_name: interpol_web
    command: python sunucu.py
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - WEB_PORT=5000