version: '3.8'

services:
  # CONTAINER C: Mesaj Kuyruğu (Postane)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: interpol_rabbitmq
    ports:
      - "5672:5672"   # Python un RabbitMQ'ya veri göndereceği port
      - "15672:15672" # Kuyruğu görsel olarak izlemek için yönetim paneli portu
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


  # CONTAINER A: Veri Çeken Üretici
  producer:
    build: .
    container_name: interpol_producer
    command: python veri_cek.py
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      PERIYOT_SANIYESI: 30


  # CONTAINER B: WEB Sunucusu ve Tüketici
  web_server:
    build: .
    container_name: interpol_web
    command: python sunucu.py
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000" # Web sunucusunun çalışacağı port
    environment:
      RABBITMQ_HOST: rabbitmq
      WEB_PORT: 5000    